### ISSUE TITLE
VESC code formatting style

### ISSUE THREAD

**Issue by ddosoff** [vedderb/bldc#114]
Hello Benjamin,

I tried to brute force formatting styles for clang-format, but can't find correct style.

What is formatting style and formatter?

**Comment by vedderb** [comment]
There is some info here in a file that was contributed a few years back:
https://github.com/vedderb/bldc/blob/master/CONTRIBUTING#L40
I'm not using a specific formatter, as they brake lines quite ugly sometimes. Mostly I use automatic line indentation only, make line breaks manually.

I should probably write some documentation about it on the VESC Project page soon, but my documentation needs significant improvements in general :-)
