### ISSUE TITLE
APP Balance - Integral Reset

### ISSUE THREAD

**Issue by DJLax5** [vedderb/bldc#117]
I have noticed that the integral is not resettet after every FAULT -> RUNNING state. 
So if you fall off and you want to start again the non-zero integral may result in unexpected behaviour.

**Comment by Mitchlol** [comment]
Good catch! I will add it to my todo list!

I should add that the I value doesn't seem to be helpful at all in this balance app implementation, and everyone I've seen myself included leave it set to 0. Regardless I will fix this.

**Comment by Mitchlol** [comment]
I don't have permissions mark it, but this issue is fixed.
