### ISSUE TITLE
3.66 / 3.67 brake issue

### ISSUE THREAD

**Issue by ddosoff** [vedderb/bldc#125]
Hello Benjamin,

It seems 3.66 breaks the brakes.
3.65 works fine.

https://www.youtube.com/watch?v=OBXvh2Qlhew

P.S. I wrote you email with this issue some days ago, but it seems lost.

**Comment by vedderb** [comment]
I noticed this too, it is due to the new integrator windup protection in the current controller. The next version will have a fix.

**Comment by vedderb** [comment]
Fixed in FW 4.00.

**Comment by ddosoff** [comment]
Now works fine, thanks!
