### ISSUE TITLE
Unreported Unbalance fault at startup

### ISSUE THREAD

**Issue by Jfriesen222** [vedderb/bldc#129]
I've noticed some drivers will record a current unbalance rate fault on startup during the time when the DC_CAL samples are being taken.  The fault isn't logged but I'd propose it shouldn't blink the LEDs either. 

There's two methods to fix it both of which make some sense,

1) In the adc interrupt have a return statement right after the current measurements are summed if dc_cal isnt done, might be safe to not do anything if that hasn't been completed. 

2) Initialize the curr_ofs to 2048 instead of 0. Have to use for loop instead of memset I think since it only does 1 byte (I think). You could also #define an expected current offset value or something to be more general.

**Comment by vedderb** [comment]
Thanks for noticing. I went with initializing to 2048, will be fixed in the next push.
