### ISSUE TITLE
<time.c>There may be cases where the time difference is negative

### ISSUE THREAD

**Issue by yenext** [vedderb/bldc#134]
When the first timestamp (TIM5->CNT) is close to 0xffffffff
uint32_t timer_time_now(void) {
	return TIM5->CNT;
}
The second timestamp is recorded when the timer expires. time > CNT? 
float timer_seconds_elapsed_since(uint32_t time) {
	uint32_t diff = TIM5->CNT - time;
	return (float)diff / (float)TIMER_HZ;
}

**Comment by kalvdans** [comment]
An uint32_t can never become negative, even when cast to a float.

**Comment by yenext** [comment]
Thank you for answering my doubts, I have ignored the processing of data type conversion.
