### ISSUE TITLE
NRF Driver incorrectly sends MOTE_PACKET_FILL_RX_BUFFER_LONG

### ISSUE THREAD

**Issue by shnads** [vedderb/bldc#14]
In nrf_driver.c the function nrf_driver_send_buffer will send a MOTE_PACKET_FILL_RX_BUFFER_LONG packet even when the data size is smaller than 255 bytes. 

To show this in practice here is the output from my logging on the receiving side:

Sending request for mc_values.
Packet received, FILL_RX_BUFFER, position: 0, packet length: 25
Packet received, FILL_RX_BUFFER, position: 23, packet length: 25
Packet received, FILL_RX_BUFFER, position: 46, packet length: 12
Packet received, FILL_RX_BUFFER_LONG, position: 46, packet length: 13
Packet received, PROCESS_RX_BUFFER, buffer length: 56, packet length: 5

Thank you for all the hard work, your ESC is brilliant. If you don't have time to fix this please let me know and I will prepare a pull request.

**Comment by vedderb** [comment]
Thanks for letting me know. This is now fixed in my local firmware, so the next time I push the code it should work properly.
