### ISSUE TITLE
Possible miss behavior in correct_hall()

### ISSUE THREAD

**Issue by ddosoff** [vedderb/bldc#157]
Hello Benjamin,

I checked the code with PVS-Studio static  analyzer.

Here are some points:

https://github.com/vedderb/bldc/blob/master/mcpwm_foc.c#L3344 - Expression 'ang_hall_int_prev == - 2' is always false.

Because here https://github.com/vedderb/bldc/blob/master/mcpwm_foc.c#L3333 type of m_conf->foc_hall_table is **unsigned**.

**Comment by vedderb** [comment]
ang_hall_int_prev is assigned to -1 and -2 just below when not using the hall table, so that code is correct. The hall interpolation is updated  a lot it FW5 anyway, so this code is outdated.

**Comment by nitrousnrg** [comment]
The static analyzer was right, I found that line a few weeks ago (https://github.com/vedderb/bldc/pull/143#discussion_r395994430)

Keep the discoveries coming!

**Comment by vedderb** [comment]
Looked at the old code now, and the assignment before the if statement should have been after it, which is the actual mistake. Anyway, this function is completely updated in fw5, so it does not matter.

**Comment by ddosoff** [comment]
I tested fw 5.0, seems really good improvement in hall positioning. Thanks!
