### ISSUE TITLE
No UART Output on VESC6 MKIV FW5.1

### ISSUE THREAD

**Issue by Timot05** [vedderb/bldc#227]
Hi Everyone,

I'm desperately trying to make the UART output and input work on my VESC6. I currently have a VESC6 MKIV from Trampa Boards with FW (firmware) 5.1. I have tried all the configurations I can on the vesctool to try and get a UART signal output but nothing seems to work. I am monitoring the TX pin with an oscilloscope to see if any signal appears, but unfortunately the pin stays high all the time.

Can anyone help me with this issue?

Thank you!

**Comment by ddosoff** [comment]
VESC will reply to UART TX if receive packet via UART RX. Try to send packet at 115200 and see for reply.

**Comment by Timot05** [comment]
Right, it works now. Thanks a lot!
