### ISSUE TITLE
Add CAN_BAUD_100K baudrate

### ISSUE THREAD

**Issue by Peemouse** [vedderb/bldc#244]
Hi,

I'd like to use a VESC with the CAN analyzer feature for reverse engineering a car.
The problem is that the targeted bus is set at a 100kbps baudrate.

I wish I could add it by my own.
However, I'm not familiar with CANbus timings and I can't retrieve the used values on the documentation I found (so impossible to understand the logic behind them).

What would be timing parameters (brp, ts1, ts2) for a 100kbps baudrate ?
Thanks a lot Ben !

Cheers,

Clément

**Comment by vedderb** [comment]
Added it just now! Let me know if it works :+1:

**Comment by Peemouse** [comment]
Wow ! Fast as light !! Thanks a lot !
