### ISSUE TITLE
Is this an typo BUG? 

### ISSUE THREAD

**Issue by BisonLeo** [vedderb/bldc#261]
https://github.com/vedderb/bldc/blob/3a071cee2f76db24308a9fb00b7d7482748ef73d/packet.c#L82

Maybe there's no such packet sent yet?

**Comment by BisonLeo** [comment]
Anyone encountered this issue when sending large packet?

**Comment by vedderb** [comment]
It is a typo. There are no packets with that size though, so it should not have an impact at the moment. Well spotted.
