### ISSUE TITLE
Hoverboard

### ISSUE THREAD

**Issue by vfear** [vedderb/bldc#268]
Hello, very cool project !!!  Thank you very much!  
Have you thought about hoverboard motherboards?  Is it possible to use the vesc tool with such hoverboard boards?  it would be amazing. 
(sorry if I don't understand something)
![image](https://user-images.githubusercontent.com/12184628/112519061-0d7aae80-8dab-11eb-9f4f-6b01c3d61b13.jpeg)

**Comment by vedderb** [comment]
Those use a completely different firmware, so unfortunately that is impossible.
