### ISSUE TITLE
incorrect eeprom emulation page transfer

### ISSUE THREAD

**Issue by hercek** [vedderb/bldc#27]
I think you need this patch for eeprom emulation in flash to properly transfer a page:
```patch
--- a/conf_general.c
+++ b/conf_general.c
@@ -42,7 +42,7 @@ void conf_general_init(void) {
 	memset(VirtAddVarTab, 0, sizeof(VirtAddVarTab));
 
 	int ind = 0;
-	for (unsigned int i = 0;i < (sizeof(app_configuration) / 2);i++) {
+	for (unsigned int i = 0;i < (sizeof(mc_configuration) / 2);i++) {
 		VirtAddVarTab[ind++] = EEPROM_BASE_MCCONF + i;
 	}
```
Also you should ensure that NB_OF_VAR has at least the size of:
`((sizeof(mc_configuration)+1)/2 + (sizeof(app_configuration)+1)/2)`

**Comment by vedderb** [comment]
You are right, I didn't notice that. Thanks! I also set NB_OF_VAR using sizeof now, which is the obvious thing to do of course.
