### ISSUE TITLE
[feature request] Software direction reverse?

### ISSUE THREAD

**Issue by l29ah** [vedderb/bldc#35]
It would be awesome to be able to switch the "primary" direction of the motor without having to rewire the motor connection (and re-detect its sensors in case of the sensorful operation). Can you advise me on the required code modifications? I'm afraid to burn the motor and VESC MOSFETs or do lots of extra work (even `mcpwm.c` looks quite complex, and it seems like I need modify much more than `set_next_comm_step()`).

**Comment by DieBieEngineering** [comment]
Software direction change is already implemented in the latest (not yet publicly available ) version of the VESC firmware. Which if I understood correctly will be released in a couple of weeks. I know its not an answer to your question, I just wanted to point out that there is a significant update coming!

**Comment by l29ah** [comment]
Oh, good to know, thank you!

**Comment by vedderb** [comment]
Implemented a while ago, closing.
