### ISSUE TITLE
Incorrect sizeof() in flash initialization code

### ISSUE THREAD

**Issue by aleph6502** [vedderb/bldc#37]
Shouldn't be sizeof(mc_configuration) (instead of app_configuration) in this line?

https://github.com/vedderb/bldc/blob/1655c11f043103352e33f1234fd32714e3ef47ff/conf_general.c#L50

Eeprom read and write is working nice, although.

**Comment by vedderb** [comment]
Seems to be fixed, must have noticed at some point.
