### ISSUE TITLE
ST-LINK 2.1 and OpenOCD

### ISSUE THREAD

**Issue by st0rfrasarn** [vedderb/bldc#389]
Hi,

For anyone trying to flash via OpenOCD using ST-LINK 2.1 i had to change the following in the Makefile to make it work:

From: 
openocd -f board/stm32f4discovery.cfg -c "reset_config trst_only combined" -c "program build/$(PROJECT).elf verify reset exit"

To:
openocd -f board/stm32f429disc1.cfg -c "reset_config trst_only combined" -c "program build/$(PROJECT).elf verify reset exit"

**Comment by Teslafly** [comment]
I remember having to update the openocd board at some point too. but don't anymore.  I believe the fix was to upgrade the stlink firmware or upgrade openocd.

Are you using the stm32f4 discovery board?

is there any reason to keep this issue open?

**Comment by st0rfrasarn** [comment]
Sorry did not get any notification about the reply. 

No, problem went away when i flashed. You can close this 😃
