### ISSUE TITLE
BESC G2 responds differently now with INVERTED_SHUNT_POLARITY

### ISSUE THREAD

**Issue by gowrav** [vedderb/bldc#400]
The BESC G2 conf file linked here https://github.com/galpavlin/BESC-G2/tree/master/firmware/hwconf works well with BETA75 of dev_fw_5_03 when added with` #define INVERTED_SHUNT_POLARITY`. however the latest version BETA77 fails with the same showing Absolute_Max_Current cutoff.

Somehow it works well without the ` #define INVERTED_SHUNT_POLARITY.`
need some clarity on this.

Also kindly include the configurations with the default build if that's possible.

**Comment by kubark42** [comment]
@gowrav did this problem get resolved?

**Comment by gowrav** [comment]
> The new firmware handles this properly.
