### ISSUE TITLE
Cant Build 5.03

### ISSUE THREAD

**Issue by preamptive** [vedderb/bldc#481]
Sorry if this is a stupid question but I cant seem to build the 5.03 branch. I can build and upload the Master branch firmware using the Beta version of Vesc tool and I've tried switching to git checkout origin/release_5_03 but this doesnt seem to work. What am I missing? Thanks in advance. K

**Comment by Teslafly** [comment]
The way to build has been changed in the current master since the last release. You need to set up the compiler manually in Linux or wsl according to the Readme on that branch. Setups for the old release will not work with the current master.

**Comment by preamptive** [comment]
Thanks
