### ISSUE TITLE
Sometimes the motor runs backwards.

### ISSUE THREAD

**Issue by secupol** [vedderb/bldc#494]
When set the sensor mode to HFI(45Deg or Coupled)
Sometimes the motor runs backwards.

**Comment by vedderb** [comment]
In that case it needs more start voltage to resolve the initial ambiguity:

![bild](https://user-images.githubusercontent.com/2311760/168253762-92a4484f-dd56-43b1-9904-4763ac6a7d88.png)

Also note that the input voltage has to be about 50% higher than the start voltage for it to work properly.
