### ISSUE TITLE
UAVCAN support

### ISSUE THREAD

**Issue by pavel-kirienko** [vedderb/bldc#5]
Hello @vedderb,

I observe that you've implemented support for some CAN bus protocol. Have you ever considered to support UAVCAN in this project? You can learn more here: http://uavcan.org.

Here's some information about PX4ESC - UAVCAN-powered, open source ESC:
- https://pixhawk.org/modules/px4esc
- https://github.com/PX4/px4esc

It would be beneficial for your project to stick to the standard that is already supported (or soon to be supported) by other vendors.

**Comment by console-beaver** [comment]
Hi  @vedderb,

It's been a while since original request by @pavel-kirienko. It would be great if you can consider it, thanks.

**Comment by bitmorse** [comment]
Awesome, thank you @vedderb ! The latest push includes libcanard and some status messages over UAVCAN. I was just about to start implementing this myself. Saves some time 👍

**Comment by vedderb** [comment]
No problem, sorry for taking so long. If you have any hardware that uses UAVCAN it would be great if you can give it a try, and let me know how it works. Currently I don't have any good way to test it at home.

**Comment by pavel-kirienko** [comment]
@vedderb we can provide the hardware for you; could you msg me at pavel.kirienko@gmail.com?

**Comment by console-beaver** [comment]
Have anyone tried it with recent Arducompter stack? Or VESC firmware still need some code to be written to support all required UAVCAN messsages?
