### ISSUE TITLE
No servo output on vesc six

### ISSUE THREAD

**Issue by TorMFinn** [vedderb/bldc#50]
Hello, 
I have flashed two vesc six with the servoout.bin image but no pwm signal is present on
the servo pin. In the event that the image included in the vesc_tool is wrong I have compiled my own binary with SERVO_OUT_ENABLE  1 and HW_VERSION 60 in conf_general.h but with no success.
Servo is set to "simple"

**Comment by vedderb** [comment]
Thanks for reporting, that was a bug in the firmware. It should be fixed the latest commit.
