### ISSUE TITLE
Feature request: support for one wire PAS

### ISSUE THREAD

**Issue by AkbarRamzan** [vedderb/bldc#525]
Currently only quadrature sensors are supported but many (cheaper) PAS sensors use only a single wire.
There are 2 signal types for one wire PAS:
One pulse every time a magnet passes when pedalling forward, no signal when pedalling backwards
One pulse of a certain width when pedalling forwards, a different width when pedalling backwards. Backwards pedalling can be used for regen.
Ideally the servo pin should be the default as uart could be used for Bluetooth / display but ebikes are unlikely to use servo.

**Comment by AkbarRamzan** [comment]
![image](https://user-images.githubusercontent.com/49323793/187968862-d0f8874c-1402-42af-8461-614a23d65198.png)

**Comment by AkbarRamzan** [comment]
https://github.com/vedderb/bldc/pull/243#issuecomment-809470359
some code for PAS that may be useful.

**Comment by AkbarRamzan** [comment]
![image](https://user-images.githubusercontent.com/49323793/210435956-6e28fdb7-a36e-44d2-8e13-5bd7212df2f7.png)
I captured the signal generated when pedalling forwards using lisp at increasing RPM
![image](https://user-images.githubusercontent.com/49323793/210436041-5bc55917-93ea-46ff-a649-6b32fc587bbb.png)
It appears back-pedalling has <50% duty cycle so you can work out pedal direction that way. Back-pedalling for regen would be nice.

**Comment by AkbarRamzan** [comment]
I'm adding support through lisp/ QML and packages. Stay tuned

**Comment by ReFeXe** [comment]
How did you manage to implement this?
Have varied width pas, when using code https://github.com/vedderb/bldc/pull/243#issuecomment-809470359 
I get triggered both ways

**Comment by ReFeXe** [comment]
> I'm adding support through lisp/ QML and packages. Stay tuned

I can't figure out how to adapt the above code

**Comment by ReFeXe** [comment]
I did it, though.
https://github.com/ReFeXe/bldclcd3/blob/release_6_02/applications/app_pas.c
