### ISSUE TITLE
App Not RUN after reboot or power cycle

### ISSUE THREAD

**Issue by trisuliswanto** [vedderb/bldc#553]
App Will Not RUN after reboot or power cycle, the reason is because in the main startup program app_set_configuration there is a check condition that will check if app has changed, and if there is no app changed the APP will not start
bool app_changed = appconf.app_to_use != conf->app_to_use;

**Comment by trisuliswanto** [comment]
I use ADC APP and it won't run, but as soon as I change another app it begin to run..

**Comment by vedderb** [comment]
I tried it with adc and adc + uart now, both start correctly after a power cycle. Do you perhaps have some script running that disables the adc-app?

**Comment by trisuliswanto** [comment]
oh sorry, it's my bad, I forget to remove #define HW_HAS_PERMANENT_NRF in my hwconf, now it start correctly.
