### ISSUE TITLE
question about naming

### ISSUE THREAD

**Issue by mcgdb** [vedderb/bldc#593]
what's `bb` mean in the drivers?  like, `i2c_bb.c` and `i2c_bb.h`.

not an issue, just curious.

**Comment by mcgdb** [comment]
can anyone provide comment on this?

**Comment by nitrousnrg** [comment]
If its not an issue, please don't raise an issue. Better place for this would be the discord server.

bb stands for bit bang. Instead of using the MCU i2c peripheral it uses a fully software-driven approach that makes it slower and cpu intensive, but is more flexible as lets you use any GPIO.
