### ISSUE TITLE
ADC3 double channels setup in hw_46.c

### ISSUE THREAD

**Issue by timtashpulatov** [vedderb/bldc#6]
In the hw_setup_adc_channels(), ADC_Channel_3 is being configured twice, in lines 131 and 133. The comment says, 'ADC3 regular channels 2, 3, 12, 3'.

Is it correct, or should it be channels 2, 3, 12 and 13?

**Comment by vedderb** [comment]
It does not matter in this case. Since the three ADCs are running in simultaneous mode, they have to sample the same amount of channels which is why "padded" the conversion group with channel 3 again. I could have used channel 13, which isn't connected, as well.
