### ISSUE TITLE
[LispBM] Shutdown event issues

### ISSUE THREAD

**Issue by dcodeIO** [vedderb/bldc#686]
As a follow-up to #666, I found that when using `shutdown-hold`, depending on how fast the power switch is cycled, shutdown respectively shutdown cancellation is not working reliably.

For example, when delaying shutdown with `shutdown-hold true`, then switching the power button on again while still performing the desired shutdown operation that would end with a `shutdown-hold false`, the VESCs will stay on as expected but (iiuc) the gate remains disabled, so it is no longer possible to drive the motors. It also appears that once in this state, the power switch is no longer functioning, so the VESCs will remain on (i.e. cannot be turned off) regardless of power switch state unless manually removed from power.

To illustrate:

![VESC-shutdown drawio](https://github.com/vedderb/bldc/assets/1136893/cb903d4b-3140-49ba-9ff4-0614991a6f31)

Perhaps the power switch is no longer sampled, and gate reactivation logic does not trigger because the shutdown operation now takes longer? Mostly guessing at this point, though :)

**Comment by vedderb** [comment]
The intention is to enable the gates and abort shutdown if it does not succeed after two seconds (as can happen of the button is toggled in-between). Maybe there is something wrong in the logic though. Can you describe the exact steps to reproduce the problem together with a small example lbm program?

**Comment by dcodeIO** [comment]
I don't have a functioning setup at hand right now, unfortunately, but I would imagine that the following program should demonstrate the issue:

```lisp
(defun do-startup () {
  (looprange i 0 5 {
    (set-duty 0.1)
    (yield 500000)
  })
  (set-duty 0.0)
})

(defun do-shutdown () {
  (looprange i 0 5 {
    (set-duty -0.1)
    (yield 500000)
  })
  (set-duty 0.0)
})

(do-startup)

(event-register-handler (self))
(event-enable 'event-shutdown)

(loopwhile true
  (recv
    (event-shutdown {
      (shutdown-hold true)
      (print "Performing action upon shutdown...")
      (do-shutdown)
      (print "Action complete. Shutting down...")
      (shutdown-hold false)
      ; LBM should terminate now unless
      ; power has been switched back on.
      (yield 500000)
      (print "Shutdown cancelled. Restarting...")
      ; If cancelled, this should work:
      (do-startup)
    })
  )
)

(unreachable)
```

Upon boot, motor should drive forwards for a bit. Upon shutdown, motor should drive backwards for a bit before the VESC is turned off. Issues appears to arise when cycling the power switch between `shutdown-hold true` and `shutdown-hold false`, in that motors won't move anymore and/or the VESC won't turn off afterwards.

Will take a closer look as soon as I have a working setup again, but perhaps that's helpful already?

**Comment by dcodeIO** [comment]
Got around to testing again meanwhile. Appears that the above program is too stripped-down to show the issues originally described. Will try to improve. However, it seems to show that the shutdown event is emitted only once, whereas subsequent toggles skip the event and shut the VESC down immediately.

Btw, I forgot to mention that the power switch setting used is `ALWAYS_OFF`. Using a 60_75_MK2 atm, 6.05 beta 22.

**Comment by dcodeIO** [comment]
Turns out that the responsiveness issues might have been something on my end, whereas the latter issue can reliably be reproduced:

* When receiving `event-shutdown` in power switch mode `ALWAYS_OFF`, set `shutdown-hold true` and turn the power switch on again while it is set to `true` (and the VESC is performing some longer action), effectively cancelling the shutdown action. When `shutdown-hold false` is invoked eventually, the VESC remains turned on as expected.
* Repeat the previous step. This time, however, the VESC will just turn off and not emit `event-shutdown` again, not providing an opportunity to `shutdown-hold true` a second time, in effect leaving the overall system in an undefined state as a consequence of not shutting down gracefully.

Unfortunately, I wasn't able to pinpoint what's causing this behavior yet. Tried a few changes to the firmware, adding `HW_SHUTDOWN_HOLD_ON` and/or `ENABLE_GATE` in suspicious places, but so far to no avail.

HW is 60_75, FW origin/master (beta 24).

**Comment by dcodeIO** [comment]
Found a hackish way to mitigate the issue. Using the following test program

```lisp
(def busy false)

(loopwhile-thd 160 true {
  (set 'busy true)
  (puts "Busy for 10 seconds...")
  (set-duty 0.1)
  (yield 10000000)
  (set-duty 0.0)
  (set 'busy false)
  (puts "Idle for 3 seconds...")
  (yield 3000000)
})

(loopwhile-thd 160 true {
  (if busy (timeout-reset))
  (yield 100000)
})

(defun event-handler ()
  (loopwhile true
    (recv
      (event-shutdown {
        (puts "Shutdown event received")
        (shutdown-hold true)
        (if busy {
          (puts "Waiting to become idle...")
          (loopwhile busy {
            (puts "...")
            (yield 1000000)
          })
          (puts "Now idle.")
        })
        (puts "Shutdown.")
        (shutdown-hold false)
        ; LBM should terminate now unless
        ; power has been switched back on.
        (yield 500000)
        (puts "Shutdown cancelled")
        (shutdown-undo) ; <-- HERE
      })
    )
  )
)

(def event-handler-id (spawn event-handler))
(event-register-handler event-handler-id)
(event-enable 'event-shutdown)
```

where `shutdown-undo` is a custom extension doing

```c
static lbm_value ext_shutdown_undo(lbm_value *args, lbm_uint argn) {
	(void)args; (void)argn;
	HW_SHUTDOWN_HOLD_ON();
	ENABLE_GATE();
	SHUTDOWN_SET_SAMPLING_DISABLED(false);
	return ENC_SYM_TRUE;
}
```

the issue can be mitigated. Not a proper fix, but seems to indicate that one of these settings is not reset when shutdown is cancelled for the first time, so the second time the VESC just turns off.
