### ISSUE TITLE
Field Weakening

### ISSUE THREAD

**Issue by nitrousnrg** [vedderb/bldc#76]
We need to provide firmware support for Field Weakening, which allows a motor to spin beyond its base speed at full power.

![image](https://user-images.githubusercontent.com/309472/53501704-67ed9780-3a8b-11e9-95fa-08e88677b662.png)

An implementation example:
![image](https://user-images.githubusercontent.com/309472/53502219-653f7200-3a8c-11e9-82f3-99337f82e9b8.png)

Deep FW operation is not efficient in small BLDC motors, but for IPM motors (issue #73) it is mandatory to go beyond base speed for full utilization of the machine, even if power drops a bit due to Id current losses.

Note this feature is ***not safe*** for most hardware implementations because it requires the powerstage to be able to withstand high motor BEMF voltages and some special fault management has to take place.

**Comment by jokucale** [comment]
Hello does this field  weaking feature work with ebike hub motors
