### ISSUE TITLE
Encoder detection oveheats the motor

### ISSUE THREAD

**Issue by flytrex-vadim** [vedderb/bldc#78]
New in FW3.50 - motor overheats during encoder detection. Works fine on the same setup in FW3.40.

Data shows very small current (less than 5%) but large duty cycle (~50%)

**Comment by vedderb** [comment]
That is actually a bug in VESC Tool, I saw it yesterday myself. It was there all along, but was not triggered before. It will be fixed in version 1.05 in the next days.
